version: "3"

services:
  database:
    container_name: bdd
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Inventaire-nws
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - mysql:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
  nginx:
    container_name: nginxsite1
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
  php:
    container_name: symfonysite
    build:
      context: .
    ports:
      - "9000:9000"
    volumes: 
      - ./:/var/www/html
    depends_on:
      - database
volumes:
  mysql:
