name: CD
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - run: ssh ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST }} "cd inventaire-nws && git pull"
      - run: ssh ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST }} "cd nventaire-nws && docker compose up -d --build --force-recreate"
name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - run: ssh ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST }} "cd inventaire-nws && git pull"
      - run: ssh ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST }} "cd nventaire-nws && docker compose up -d --build --force-recreate"
