name: CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          docker compose up -d
          docker compose exec php composer install
          docker compose exec php php bin/console doctrine:database:create --env=test
          docker compose exec php php bin/console doctrine:schema:update --env=test --force
          docker compose exec php php bin/phpunit

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: login to github container regestry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push to github registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/maxime-louis14/inventaire-nws-php:latest
          target: inventaire

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker compose up -d
      - run: docker compose exec php composer install
      - run: docker compose exec php php bin/console doctrine:database:create --env=test
      - run: docker compose exec php php bin/console doctrine:schema:update --env=test --force
      - run: docker compose exec php php bin/phpunit
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd inventaire-nws && git pull"
      - run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd inventaire-nws && docker compose up -d --build"
