name: Symfony

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - run: docker compose up -d 
        - run: docker compose exec php composer install
        - run: ls -lah vendor/symfony/phpunit-bridge/bin/
        - run: docker compose exec php php bin/phpunit