name: Symfony

on:
  push:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - run: docker compose up -d 
        - run: docker compose exec php composer install
        - run: docker compose exec php symfony console doctrine:database:create --env=test
        - run: docker compose exec php symfony console doctrine:migrations:migrate --env=test
        - run: docker compose exec php php bin/phpunit  
