on: [push]
name: Build and test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          docker compose up -d
          docker compose exec php composer install
          docker compose exec php php bin/console doctrine:database:create --env=test
          docker compose exec php php bin/console doctrine:schema:update --env=test --force
          docker compose exec php php bin/phpunit